---
driver:
  name: vagrant
  customize:
    memory: 2048

provisioner:
  name: chef_solo
  require_chef_omnibus: 12

platforms:
#  - name: centos-6.7
#    driver:
#      network:
#      - ["forwarded_port", {guest: 8080, host: 9000}]
  - name: centos-7.1
    driver:
      network:
      - ["forwarded_port", {guest: 9000, host: 9000}]
      - ["forwarded_port", {guest: 8080, host: 8080}]
#  - name: ubuntu-14.04
#    driver:
#      network:
#      - ["forwarded_port", {guest: 8080, host: 9003}]

suites:
- name: default
  run_list:
    - play_test::default
    - play_test::tar
  attributes:
