---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: centos-6.7
  driver:
    network:
    - ["forwarded_port", {guest: 8080, host: 9000}]
- name: centos-7.1
  driver:
    network:
    - ["forwarded_port", {guest: 8080, host: 9001}]
- name: ubuntu-12.04
  driver:
    network:
    - ["forwarded_port", {guest: 8080, host: 9002}]
- name: ubuntu-14.04
  driver:
    network:
    - ["forwarded_port", {guest: 8080, host: 9003}]

suites:
- name: play
#  encrypted_data_bag_secret_key_path: <%= ENV['ENCRYPTED_DATA_BAG_SECRET'] %>
#  data_bags_path: <%= ENV['MERLE'] %>/data_bags
  run_list: ["recipe[play_test::default]"]
  attributes: {
    "play": {
      "config_variables": {
        "secret": "mysecret"
      },
      "args": [
        "-Dhttp.port=8080",
        "-J-Xms128M",
        "-J-Xmx512m",
        "-J-server"
      ]
    }
  }
