---
driver:
  name: vagrant
  customize:
    memory: 2048

provisioner:
  name: chef_solo
  require_chef_omnibus: 11

platforms:
  - name: centos-6.7
    driver:
      network:
      - ["forwarded_port", {guest: 8080, host: 9000}]
  - name: centos-7.1
    driver:
      network:
      - ["forwarded_port", {guest: 8080, host: 9001}]
  - name: ubuntu-12.04
    driver:
      network:
      - ["forwarded_port", {guest: 8080, host: 9002}]
  - name: ubuntu-14.04
    driver:
      network:
      - ["forwarded_port", {guest: 8080, host: 9003}]

suites:
- name: default
  run_list:
    - recipe[play_test]
  attributes: {
    "play": {
      "servicename": "sample_service",
      "source": "https://github.com/dhoer/play-java-sample/releases/download/1.0/play-java-sample-1.0.zip",
      "conf_variables": {
        "secret": "mysecret"
      },
      "args": [
        "-Dhttp.port=8080",
        "-J-Xms128M",
        "-J-Xmx512m",
        "-J-server"
      ]
    }
  }
